# Generated by Django 5.0.7 on 2024-07-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="video_file",
            new_name="file",
        ),
        migrations.RemoveField(
            model_name="video",
            name="uploaded_by",
        ),
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
